services:
  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - minha-rede

  projectmanager:
    container_name: projectmanager
    build:
      context: ./ProjectManager/src
      dockerfile: ProjectManager.Presentation/Dockerfile
    ports:
      - "5010:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DatabaseSettings__ConnectionString=${DB_CONNECTION_STRING}
      - DatabaseSettings__DatabaseName=${DB_NAME}
    depends_on:
      - mongo_db
    networks:
      - minha-rede

volumes:
  mongo_data:
    driver: local 

networks:
  minha-rede:
    driver: bridge
